### ISSUE TITLE
Updated Java to 21, got this warn

### ISSUE THREAD

**Issue by Dreig-Michihi** [SkriptLang/AddonPatcher#3]
![image](https://github.com/SkriptLang/AddonPatcher/assets/60939608/15782e60-3cc2-4a37-a12a-49d33fb58067)

**Comment by EquipableMC** [comment]
Can you sent the output of what Java version your using when the server first starts?

**Comment by Dreig-Michihi** [comment]
> Can you sent the output of what Java version your using when the server first starts?

![image](https://github.com/SkriptLang/AddonPatcher/assets/60939608/4f3a390a-038b-450b-a59d-909103f914b2)

**Comment by Dreig-Michihi** [comment]
> Can you sent the output of what Java version your using when the server first starts?

We use Agent version

**Comment by Dreig-Michihi** [comment]
> Can you sent the output of what Java version your using when the server first starts?

Will you fix that?

**Comment by Dreig-Michihi** [comment]
@EquipableMC 
![image](https://github.com/user-attachments/assets/23696ebf-cb0f-4214-ad2a-4eae3beadf57)
whole console spammed with it, especially on server start

**Comment by EquipableMC** [comment]
> @EquipableMC ![image](https://private-user-images.githubusercontent.com/60939608/364948533-23696ebf-cb0f-4214-ad2a-4eae3beadf57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NzEzNDksIm5iZiI6MTcyNTU3MTA0OSwicGF0aCI6Ii82MDkzOTYwOC8zNjQ5NDg1MzMtMjM2OTZlYmYtY2IwZi00MjE0LWFkMmEtNGVhZTNiZWFkZjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDIxMTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3YWY1NTQyMDA0MDc5NDFkODk3M2I2OGUyMmIyMmViNDBjYjczYmJkNDNmZjY3ODE1NzRlZGFhNTU4OWFjMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LUzm3RWHVobBPVfoCT8S7JmgA5BVyH1lQ_sBdPFMZT8) whole console spammed with it, especially on server start

your server is clearly not using java 21, hence these errors.

**Comment by sovdeeth** [comment]
> > @EquipableMC ![image](https://private-user-images.githubusercontent.com/60939608/364948533-23696ebf-cb0f-4214-ad2a-4eae3beadf57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NzEzNDksIm5iZiI6MTcyNTU3MTA0OSwicGF0aCI6Ii82MDkzOTYwOC8zNjQ5NDg1MzMtMjM2OTZlYmYtY2IwZi00MjE0LWFkMmEtNGVhZTNiZWFkZjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDIxMTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3YWY1NTQyMDA0MDc5NDFkODk3M2I2OGUyMmIyMmViNDBjYjczYmJkNDNmZjY3ODE1NzRlZGFhNTU4OWFjMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LUzm3RWHVobBPVfoCT8S7JmgA5BVyH1lQ_sBdPFMZT8) whole console spammed with it, especially on server start
> 
> your server is clearly not using java 21, hence these errors.

This is not relevant to the issue
The issue is addon-patcher is not recognizing classes compiled with java 21 or whatever 65 refers to

**Comment by abandonedaccount6235** [comment]
can you try this version?

https://github.com/SkriptLang/AddonPatcher/actions/runs/10729370130/artifacts/1898793351

**Comment by Dreig-Michihi** [comment]
> can you try this version?
> 
> https://github.com/SkriptLang/AddonPatcher/actions/runs/10729370130/artifacts/1898793351

Thank you, no WARNs anymore. I'll let you know, if there'll be some issues

**Comment by abandonedaccount6235** [comment]
yay, thank you
